# This is a basic workflow to help you get started with Actions

name: Containerize C Application and push it to Docker Hub 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Containerize-C-Application:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
     
      - name: Is gcc Installed? 
        run: gcc --version
        
      - name: Compile C-code to a binary
        run: gcc -o helloworld hello.c
        
      - name: Run The built binary and observe that “hello world” is printed in the terminal
        run: ./helloworld
        
      - name: List files 
        run: ls -a 
        
      - name: Build The docker image
        run: docker build -t hello:latest .
        
      - name: List Docker Images
        run: docker images
        
      - name: run a container using The Building image
        run: docker run hello:latest
 
      - name: Login To Docker Hub
        run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: echo docker username and passswd
        run : echo "${{ secrets.DOCKER_USERNAME }}  ${{ secrets.DOCKER_PASSWORD }}"

        
        
